// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvwd7VgroiTCX98hvXF6eAFyhUcnEan4',
    appId: '1:480764495103:web:50ff3b7254f5d0518e38ca',
    messagingSenderId: '480764495103',
    projectId: 'maakanmoney-a6874',
    authDomain: 'maakanmoney-a6874.firebaseapp.com',
    databaseURL: 'https://maakanmoney-a6874-default-rtdb.firebaseio.com',
    storageBucket: 'maakanmoney-a6874.appspot.com',
    measurementId: 'G-NYVDKWK7NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUmqkw5lQ6nC06opFAIsxFXuSn4VwDlPA',
    appId: '1:480764495103:android:864f18ad3b7f1b6b8e38ca',
    messagingSenderId: '480764495103',
    projectId: 'maakanmoney-a6874',
    databaseURL: 'https://maakanmoney-a6874-default-rtdb.firebaseio.com',
    storageBucket: 'maakanmoney-a6874.appspot.com',
  );
  // dAzrpQk0Ta-EdorIC32lLX:APA91bGLNylTsMm07qYgVhUFN0EvPJsy1ozPwWZCMBQWadzlp_hqAbmlfncDYHjZ5hmr4KCtPP4gqcVqQoasIvtA4ZaaH9z7OcXy9PxPTqjA3VULRMhKoGz1RVh4Esr_Uypx55L8kYfA
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nz3Q2jn0BdEJW6a4PqesMT9cqUtXDbg',
    appId: '1:480764495103:ios:ab62db3b75001bdd8e38ca',
    messagingSenderId: '480764495103',
    projectId: 'maakanmoney-a6874',
    databaseURL: 'https://maakanmoney-a6874-default-rtdb.firebaseio.com',
    storageBucket: 'maakanmoney-a6874.appspot.com',
    iosBundleId: 'com.maaakanmoney.mm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nz3Q2jn0BdEJW6a4PqesMT9cqUtXDbg',
    appId: '1:480764495103:ios:73799562226700bc8e38ca',
    messagingSenderId: '480764495103',
    projectId: 'maakanmoney-a6874',
    databaseURL: 'https://maakanmoney-a6874-default-rtdb.firebaseio.com',
    storageBucket: 'maakanmoney-a6874.appspot.com',
    iosBundleId: 'com.maaakanmoney.samplefirebase.RunnerTests',
  );
}
